### ISSUE TITLE
Using a hidden file as manifest file

### ISSUE THREAD

**Issue by denzelem** [makandra/precompiled_assets#2]
In https://github.com/rails/propshaft/blob/e7cdbcd4aa9c9a390dade263bbd7c7cedc0c6442/lib/propshaft/processor.rb#L4 propshaft uses a hidden file as manifest file. IMHO this is a better default in terms of security. 

* The `public/assets/.manifest` is not delivered by webservers
* Is is not possible to inspect all assets of an application (e.g. reading backend JS code to understand a companies business logic)

Requires a breaking change when used with Capistrano:

```
set :assets_manifests, lambda {
  [release_path.join('public', fetch(:assets_prefix), '.manifest.json')]
}
```

Wdyt?

**Comment by makmic** [comment]
We did not see a general demand / use case for this feature (which would require quite a bit of complexity to implement).
Therefore we decided against it for now.

You can however adjust your Apache/Nginx configuration to exclude the manifest file from being delivered (via a .htaccess file or other rule). Would that already solve your use case?

**Comment by denzelem** [comment]
> You can however adjust your Apache/Nginx configuration to exclude the manifest file from being delivered (via a .htaccess file or other rule). Would that already solve your use case?

Thanks. I'm closing this issue for now.
